id: your_first_step
startFlow:
  do:
    - actionId: bot_message
      params:
        person: keen
        messages:
          - text: Hello world
            delay: 3000
trigger:
  type: user_message
  params:
    person: keen
  flowNode:
    do:
      - actionId: finish_step
